app = 'test-ictadmission'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048

[[mounts]]
  source = "datavol"
  destination = "/data"
